#!/bin/bash

#$1 = '$file_name'
#$2 = '${file_base_name}'

##################A projekt paraméterei:################
fordito="g++"
projectfileok="main.cpp"
parameterek="-std=c++14 -Lflugigraph -Iflugigraph -lgraphics -lSDL -lSDL_ttf -Iwidget -Ilua5.3.4/include -Llua5.3.4/lib -ILuaBridge -lm -llua -ldl -lpthread"
nev="main.run"
futtatas=true
########################################################



################Fordítás és futtatás:###################
if [[ ! -d "bin" ]]; then
	mkdir "bin"
fi

nev="bin/$nev"

if [ -f $nev ]; then ## Biztonsági mentés
    mv $nev $nev".bak";
fi

$fordito $projectfileok $parameterek "-o" $nev

if [[ $futtatas && -f $nev ]]; then
	timeout 4s gnome-terminal -x $nev;
fi
########################################################